//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons_n_Dragons_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons_n_Dragons_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded
        ///Leather
        ///Studded Leather
        ///Hide
        ///Chain Shirt
        ///Scale Mail
        ///Breastplate
        ///Half Plate
        ///Ring Mail
        ///Splint
        ///Plate.
        /// </summary>
        internal static string ArmorTypes {
            get {
                return ResourceManager.GetString("ArmorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian
        ///Bard
        ///Cleric
        ///Druid
        ///Fighter
        ///Monk
        ///Paladin
        ///Ranger
        ///Rogue
        ///Sorcerer
        ///Warlock
        ///Wizard.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic;Coastal;Desert;Forest;Grassland;Hill;Mountain;Swamp;Underdark;Underwater;Urban.
        /// </summary>
        internal static string Environments {
            get {
                return ResourceManager.GetString("Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;ChallengeRating;ChallengeXP;ACType;AC;STR;STRMod;DEX;DEXMod;CON;CONMod;INT;INTMod;WIS;WISMod;CHA;CHAMod;HPDice;HP;Enviroments
        ///Adult Red Dragon;17;18000;natural armor;19;27;8;10;0;25;7;16;3;13;1;21;5;19d12 + 133;256;Hill,Mountain
        ///Stone Golem;10;5900;natural armor;17;22;6;9;-1;20;5;3;-4;11;0;1;-5;17d10 + 85;178;All
        ///Fire Giant;9;5000;plate;18;25;7;9;-1;23;6;10;0;14;2;13;1;13d12 + 78;162;Mountain,Underdark
        ///Hydra;8;3900;natural armor;15;20;5;12;1;20;5;2;-4;10;0;7;-2;15d12 + 75;172;Swamp
        ///Frost Giant;8;3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aarakocra
        ///Aasimar
        ///Bugbear
        ///Changeling
        ///Dragonborn
        ///Dwarf
        ///Elf
        ///Firbolg
        ///Genasi
        ///Gnome
        ///Goblin
        ///Goliath
        ///Halfling
        ///Half-Elf
        ///Half-Orc
        ///Hobgoblin
        ///Human
        ///Kender
        ///Kenku
        ///Kobold
        ///Kor
        ///Lizardfolk
        ///Merfolk
        ///Minotaur
        ///Orc
        ///Shifter
        ///Tabaxi
        ///Tiefling
        ///Tortle
        ///Triton
        ///Vampire
        ///Warforged
        ///Yuan-Ti Pureblood.
        /// </summary>
        internal static string Races {
            get {
                return ResourceManager.GetString("Races", resourceCulture);
            }
        }
    }
}
